version: "3.9"

services:
  controller:
    build:
      context: .
      dockerfile: controller.dockerfile
    container_name: echonet_controller
    stdin_open: true
    tty: true
    networks:
      - echonet
    environment:
      - RUST_LOG=debug

  monolight:
    build:
      context: .
      dockerfile: monolight.dockerfile
    container_name: echonet_monolight
    networks:
      - echonet
    environment:
      - RUST_LOG=debug

  ssng:
    build:
      context: .
      dockerfile: ssng.dockerfile
    container_name: echonet_ssng
    ports:
      - "3000:3000"
      - "8080:8080"
    networks:
      - echonet
    environment:
      - NODE_ENV=production
    volumes:
      - ./ssng-node2/log:/app/log

networks:
  echonet:
    driver: bridge
